#!/bin/bash

commit_lots() {
    n=0
    while [ $n -lt 200 ]; do
        n=$(expr $RANDOM % 2000)
    done
    for i in `seq $n`; do
        echo "echo $RANDOM puppies" >>puppy
        git add puppy
        git commit -m'add more puppies'
    done
}

commit_lots

echo 'echo one dead puppy' >>puppy
git add puppy
git commit --author 'Bad Programmer <bprogrammer@coalfire.com>' -m'add more puppies'


commit_lots
